import React from 'react';
import Head from "next/head";
import Image from "next/image";
import LogoImage from "../../assets/images/pokemon-logo.png";
import Link from 'next/link';

const Layout = ({children, title}) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div id='navbar'>
                <Image src={LogoImage} alt="logo" width={350} height={100} />
            </div>

            <section className="container mx-auto">
                {children}
            </section>
        </div>
    );
};

export default Layout;
