export const HandleTypeColors = (pokemon, changePokeBg) => {
    console.log('Poke: ',pokemon)
    pokemon.map((type) => {
        if (type.type.name === 'grass')
            changePokeBg('#7AC74C')
        if (type.type.name === 'normal')
            changePokeBg('#A8A77A')
        if (type.type.name === 'fire')
            changePokeBg('#EE8130')            
        if (type.type.name === 'water')
            changePokeBg('#6390F0')
        if (type.type.name === 'electric')
            changePokeBg('#F7D02C')
        if (type.type.name === 'ice')
            changePokeBg('#96D9D6')   
        if (type.type.name === 'fighting')
            changePokeBg('#C22E28')
        if (type.type.name === 'poison')
            changePokeBg('#A33EA1')
        if (type.type.name === 'ground')
            changePokeBg('#E2BF65')    
        if (type.type.name === 'flying')
            changePokeBg('#A98FF3')
        if (type.type.name === 'psychic')
            changePokeBg('#F95587')
        if (type.type.name === 'bug')
            changePokeBg('#A6B91A')    
        if (type.type.name === 'rock')
            changePokeBg('#B6A136')
        if (type.type.name === 'ghost')
            changePokeBg('#735797')    
        if (type.type.name === 'dragon')
            changePokeBg('#6F35FC')
        if (type.type.name === 'dark')
            changePokeBg('#705746')
        if (type.type.name === 'steel')
            changePokeBg('#B7B7CE')        
        if (type.type.name === 'fairy')
            changePokeBg('#D685AD')                                
    })
}